AcutronicRobotics/MARA

- hros_cognition_mara_components/CMakeLists.txt
- hros_cognition_mara_components/include/hros_cognition_mara_components/HROSCognitionMaraComponents.hpp
- hros_cognition_mara_components/test_python/move_motors.py
- individual_trajectories_bridge/CMakeLists.txt
colcon build successfull in crystal:
- individual_trajectories_bridge
- hros_cognition_mara_components
> Remove Hebi & update CMakeLists absolute path.

- mara_gazebo_plugins/src/mara_gazebo_joint_plugin.cpp
> Final fix for plugin reset

- robotiq_85_gripper_description/urdf/robotiq_85.urdf
- robotiq_85_gripper_description/urdf/robotiq_85.urdf.xacro
- robotiq_gripper_gazebo_plugins/include/robotiq_gripper_gazebo_plugins/RobotiqPlugin.h
- robotiq_gripper_gazebo_plugins/src/RobotiqPlugin.cpp
Switched the direction of certain joints.
Reduced inner_knuckle to base link joint upper limit.
Switched plugin to act on the inner finger joint instead of the inner_knuckle one.
An goal_angularposition of 0.78 closes the gripper. There's a slight separation between the fingers, might require some fine-tuning.
> Fix robotiq85 gripper urdf & plugin

- robotiq_140_gripper_description/urdf/robotiq_140.urdf
- robotiq_140_gripper_description/urdf/robotiq_140.urdf.xacro
An angular position goal of 0.76-0.77 closes the gripper as far as it goes, with 0.77+ the gripper will start twitching.
> Fix robotiq gripper 140 urdf

- robotiq_140_gripper_description/urdf/robotiq_140.urdf
- robotiq_140_gripper_description/urdf/robotiq_140.urdf.xacro
- robotiq_85_gripper_description/urdf/robotiq_85.urdf
- robotiq_85_gripper_description/urdf/robotiq_85.urdf.xacro
- robotiq_gripper_gazebo_plugins/CMakeLists.txt
- robotiq_gripper_gazebo_plugins/include/robotiq_gripper_gazebo_plugins/RobotiqLinearPlugin.h
- robotiq_gripper_gazebo_plugins/src/RobotiqLinearPlugin.cpp
- robotiq_hande_gripper_description/urdf/hande_gripper.urdf.xacro
- robotiq_hande_gripper_description/urdf/robotiq_hande.urdf
Added plugin for the linear hand-e gripper, renamed previous plugin and updated affected urdf's.
Fixed hand-e gripper urdf joints.
> Add plugin for linear gripper

- individual_trajectories_bridge/src/main.cpp
We had issues with this when creating double bridge. Not very important, though
> Typo subcriber --> subscribers

- mara-ros2.repos
- mara_description/urdf/mara_robot_gripper_140.urdf
- mara_description/urdf/mara_robot_gripper_140_run.urdf
- mara_description/urdf/mara_robot_gripper_85.urdf
- mara_description/urdf/mara_robot_gripper_hande.urdf
After the last commits in [robotiq_modular_gripper](https://github.com/AcutronicRobotics/robotiq_modular_gripper) repo, the gripper started to vibrate like this:
with this changes the 140 gripper works fine again.
> Fix gripper vibrations [WIP]

- individual_trajectories_bridge/src/main.cpp
- individual_trajectories_bridge/src/main_actions.cpp
added effort and velocity to ROS 1 joint_states
> added effort and velocity to joint_states

- mara-ros2.repos
Seems like latest commit under ros2 is failing.
> update image common to crystal

- mara_description/urdf/mara.urdf.xacro
- mara_description/urdf/mara_robot_gripper_140.urdf
- mara_description/urdf/mara_robot_gripper_85.urdf
- mara_description/urdf/mara_robot_gripper_hande.urdf
- mara_description/urdf/mara_robot_gripper_ur_j.urdf
Fixing
- inertias
- center of mass
- limits 
- efforts
> Fixing inertias, center of mass, limits and efforts

- README.md
PR from https://github.com/AcutronicRobotics/MARA/issues/15#issuecomment-475758915
> fix installation instructions

- mara-ros2.repos
use the latest release of HRIM
> Mara repos hrim

- mara_bringup/launch/mara.launch.py
- mara_bringup/launch/mara_bringup.launch.py
- mara_bringup/launch/mara_bringup_real.launch.py
- mara_description/launch/mara_demo_launch.py
- mara_gazebo/launch/mara.launch.py
- mara_gazebo/launch/mara_with_moveit_bridge.launch.py
- mara_gazebo/rviz/mara.rviz
- mara_utils_scripts/scripts/spawn_entity.py
mara_robot_camera_top.urdf does not exist anymore, replaced with mara_robot_gripper_140.urdf
> fix references to nonexistent urdf

- .ci/Dockerfile
* try three times to bring the key
> Added while statement:

- README.md
- individual_trajectories_bridge/include/FollowJointTrajectoryAction.hpp
- individual_trajectories_bridge/src/main_actions.cpp
- Added -ft_topic flag
- Usage:
```bash
ros2 run individual_trajectories_bridge individual_trajectories_bridge_actions -ft_topic /hrim_sensor_torque_70B3D521A0C2/forcetorque -motors /home/erle/ros2_mara/src/mara/hros_cognition_mara_components/config/motors.yaml real &
```
> Added support for ForceTorque sensor bridge ROS2->ROS1

- individual_trajectories_bridge/CMakeLists.txt
Co-authored-by: ahcorde <ahcorde@gmail.com>
> Fix linking errors, bridge forcetorque

- individual_trajectories_bridge/CMakeLists.txt
Signed-off-by: Lander Usategui <lander.usategui@gmail.com>
> Remove hrim_sensor_forcetorque_msgs CMakeList

- mara_description/urdf/mara_robot_gripper_140.urdf
- mara_description/urdf/mara_robot_gripper_140_no_table.urdf
- mara_description/urdf/mara_robot_gripper_85.urdf
- mara_description/urdf/mara_robot_gripper_hande.urdf
- mara_description/urdf/reinforcement_learning/mara_robot_gripper_140_camera_run.urdf
- mara_description/urdf/reinforcement_learning/mara_robot_gripper_140_camera_train.urdf
- mara_description/urdf/two_mara_robots_gripper_140_no_table.urdf
sync https://github.com/AcutronicRobotics/robotiq_modular_gripper/pull/12
> Update gripper urdfs to sync with robotiq branch

- .ci/Dockerfile
- .ci/compile.sh
- README.md
@LanderU can you change to dashing if anything else is missing? Thanks.
> switch to dashing

- mara_contact_publisher/src/ContactPublisher.cpp
Changed to rclcpp::SensorDataQoS() in order to avoid warnings when compiling
> Updated QoS for Dashing

- mara_gazebo_plugins/src/mara_gazebo_joint_training_plugin.cpp
Changed QoS policies and order when subscribing
> Updated QoS policies for Dashing

- individual_trajectories_bridge/src/main_actions.cpp
QoS policy updated for the bridge.
> Updated QoS at individual_trajectories_bridge pkg

- mara_gazebo_plugins/include/mara_gazebo_plugins/mara_gazebo_joint_plugin.hpp
- mara_gazebo_plugins/src/mara_gazebo_joint_plugin.cpp
> Allow trajectories to be interrupted interrupt [master]

- mara_gazebo_plugins/include/mara_gazebo_plugins/mara_gazebo_joint_plugin.hpp
- mara_gazebo_plugins/src/mara_gazebo_joint_plugin.cpp
Reverts AcutronicRobotics/MARA#121
> Revert "Allow trajectories to be interrupted interrupt [crystal]"
